version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  trainer:
    build: .
    container_name: trainer-python-service
    ports:
      - "50051:50051"
    environment:
      MONGODB_URI: mongodb://mongo:27017
      MONGODB_DB: TrainerDb
      MONGODB_COLL: Trainers
    depends_on:
      - mongo

volumes:
  mongo-data:
