FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 8090
ENV ASPNETCORE_URLS=http://+:8090

USER app
FROM --platform=$BUILDPLATFORM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG configuration=Release
WORKDIR /src
COPY ["PokemonApi.csproj", "./"]
RUN dotnet restore "./PokemonApi.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "PokemonApi.csproj" -c $configuration -o /app/build

FROM build AS publish
ARG configuration=Release
RUN dotnet publish "PokemonApi.csproj" -c $configuration -o /app/publish /p:UseAppHost=true 
   
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PokemonApi.dll"]
