FROM golang:1.20 AS build
WORKDIR /app

COPY go.mod ./
COPY go.sum ./
RUN go mod download

COPY . ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /chat ./CMD/chat

FROM scratch
COPY --from=build /chat /chat
ENTRYPOINT ["/chat"]